routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AddressController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CoinController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FavoriteController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentMethodController;
use App\Http\Controllers\Admin\ProductCategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductImageController;
use App\Http\Controllers\Admin\ProductPriceController;
use App\Http\Controllers\Admin\ProductSubcategoryController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ResellerController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\Admin\SliderPromoController;
use App\Http\Controllers\Admin\VoucherController;
use App\Http\Controllers\AdminLoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AdminLoginController::class, 'index'])->name('admin.login.index');
Route::post('/post', [AdminLoginController::class, 'login'])->name('admin.login');
Route::get('/logout', [AdminLoginController::class, 'logout'])->name('admin.logout');

Route::get('/', function(){
    return redirect(route('admin.login.index'));
});

Route::group(['middleware'=>'auth:admin'], function() {
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/admin', AdminController::class);
    Route::resource('/about', AboutController::class);
    Route::resource('/address', AddressController::class);
    Route::resource('/cart', CartController::class);
    Route::resource('/coin', CoinController::class);
    Route::resource('/customer', CustomerController::class);
    Route::resource('/faq', FaqController::class);
    Route::resource('/favorite', FavoriteController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/product', ProductController::class );
    Route::resource('/payment_method', PaymentMethodController::class);
    Route::resource('/product_category', ProductCategoryController::class);
    Route::resource('/product_subcategory', ProductSubcategoryController::class);
    Route::resource('/product_image', ProductImageController::class);
    Route::resource('/product_price', ProductPriceController::class);
    Route::resource('/reseller', ResellerController::class);
    Route::resource('/shipping', ShippingController::class);
    Route::resource('/slider_promo', SliderPromoController::class);
    Route::resource('/voucher', VoucherController::class);
    Route::resource('/city', CityController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/district', DistrictController::class);

    Route::delete('/product_price/wholesaler/{wholesaler}', [ProductPriceController::class, 'destroyWholesaler'])->name('wholesaler.delete');
    Route::get('/coin/{coin}/history', [CoinController::class, 'coinhistory']);
});


//Admin Home page after login

resources/views/admins/create-edit.blade.php
@extends('layout.page')

@section('title', 'Admin')

@section('header-content')

@endsection

@section('page-content')
<x-card.layout>
    <x-slot name="header">
        {{ request()->routeIs('admin.create') ? 'Create Admin' : 'Update Admin' }}
    </x-slot>
    <x-slot name="body">
        <form id="form"
            action="{{ request()->routeIs('admin.create') ? route('admin.store'): route('admin.update', @$admin->id) }}"
            class="theme-form mega-form" method="post" enctype="multipart/form-data">
            @csrf
            @isset($admin->image)
                <x-forms.view-image src="{{asset('storage/' . $admin->image)}}" />
            @endisset
            <x-forms.put-method />
            <x-forms.file label="Pilih Photo Profil" name="image" id="gallery-photo-add"/>
            <div class="gallery row row-cols-4 justify-content-center" id="isi-gallery"></div>
            <x-forms.input required="" label="Nama Lengkap" name="name" :value="@$admin->name" />
            <x-forms.input required="" label="Email" name="email" :value="@$admin->email" />
            <x-forms.input required="" label="Username" name="username" :value="@$admin->username" />
            <x-forms.text required="" label="Phone Number" type="number" name="phone" :value="@$admin->phone" />
            <x-forms.text password="1" label="Password" name="password" :value="@$admin->passwords" />
            <x-forms.select label="Tipe Admin" name="role" :items="$select_role" :value="@$admin->role" />
        </form>
        <button form="form" class="btn btn-primary btn-pill">Submit</button>
        <x-action.cancel />
    </x-slot>
</x-card.layout>
@endsection

@section('footer-content')
<script>
    $(document).ready(() => {
        //function untuk menampilkan preview image
        var imagesPreview = function(input, placeToInsertImagePreview) {

        if (input.files) {
            var filesAmount = input.files.length;

            for (var i = 0; i < filesAmount; i++) {
                var reader = new FileReader();

                reader.onload = function(event) {
                    var card = $('<div/>').attr({
                        class: 'col mx-1 card'
                    })

                    var divImage = $('<div/>').attr({
                        class: 'my-auto'
                    })

                    $($.parseHTML('<img>')).attr('src', event.target.result).attr('class', 'img-thumbnail imagePreview').appendTo(divImage);

                    divImage.appendTo(card);

                    var divFooter = $('<div/>').attr({
                        class: 'card-footer'
                    })

                    // buttonImage.appendTo(divFooter);
                    divFooter.appendTo(card);
                    card.appendTo(placeToInsertImagePreview);

                    if($('.imagePreview').length > 10){
                        alert('Upload Gambar dibatasi hingga 10 gambar')
                        return;
                    }
                }

                reader.readAsDataURL(input.files[i]);
            }
            }
        };
        //Menampilkan Thumbnail sebelum upload
        $('#gallery-photo-add').on('change', function() {
        imagesPreview(this, 'div.gallery');
        });

        //Menghapus Thumbnail apabila terdapat pergantian file upload
        $('#gallery-photo-add').on('click', function(){
        // console.log('Masuk')
        let parent = document.getElementById("isi-gallery")
        while (parent.firstChild) {
            parent.firstChild.remove()
        }
        });
    })
</script>
@endsection

resources/views/admins/index.blade.php
@extends('layout.page')

@section('title', 'Customer')

@section('header-content')

@endsection

@section('page-content')
<x-card.layout >
    <x-slot name="header">
        <x-card.h-buat url="{{route('admin.create')}}" title="Admin"/>
    </x-slot>

    <x-slot name="body">
        <table class="table table-striped">
            <thead>
                <th>No</th>
                <th>Nama</th>
                <th>Username</th>
                <th>Role</th>
                <th>Action</th>
            </thead>
            <tbody>
                @foreach ($admins as $each)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$each->name}}</td>
                        <td>{{$each->username}}</td>
                        <td>{{$each->role}}</td>
                        <td class="d-flex">
                            <x-action.edit action="{{route('admin.edit', $each->id)}}" />
                            <x-action.delete :ident="$each->id" action="{{route('admin.destroy', $each->id)}}" />
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </x-slot>
</x-card.layout>
@endsection

@section('footer-content')

@endsection