routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AddressController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CoinController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FavoriteController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentMethodController;
use App\Http\Controllers\Admin\ProductCategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductImageController;
use App\Http\Controllers\Admin\ProductPriceController;
use App\Http\Controllers\Admin\ProductSubcategoryController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ResellerController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\Admin\SliderPromoController;
use App\Http\Controllers\Admin\VoucherController;
use App\Http\Controllers\AdminLoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AdminLoginController::class, 'index'])->name('admin.login.index');
Route::post('/post', [AdminLoginController::class, 'login'])->name('admin.login');
Route::get('/logout', [AdminLoginController::class, 'logout'])->name('admin.logout');

Route::get('/', function(){
    return redirect(route('admin.login.index'));
});

Route::group(['middleware'=>'auth:admin'], function() {
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/admin', AdminController::class);
    Route::resource('/about', AboutController::class);
    Route::resource('/address', AddressController::class);
    Route::resource('/cart', CartController::class);
    Route::resource('/coin', CoinController::class);
    Route::resource('/customer', CustomerController::class);
    Route::resource('/faq', FaqController::class);
    Route::resource('/favorite', FavoriteController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/product', ProductController::class );
    Route::resource('/payment_method', PaymentMethodController::class);
    Route::resource('/product_category', ProductCategoryController::class);
    Route::resource('/product_subcategory', ProductSubcategoryController::class);
    Route::resource('/product_image', ProductImageController::class);
    Route::resource('/product_price', ProductPriceController::class);
    Route::resource('/reseller', ResellerController::class);
    Route::resource('/shipping', ShippingController::class);
    Route::resource('/slider_promo', SliderPromoController::class);
    Route::resource('/voucher', VoucherController::class);
    Route::resource('/city', CityController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/district', DistrictController::class);

    Route::delete('/product_price/wholesaler/{wholesaler}', [ProductPriceController::class, 'destroyWholesaler'])->name('wholesaler.delete');
    Route::get('/coin/{coin}/history', [CoinController::class, 'coinhistory']);
});


//Admin Home page after login

app/Models/Reseller.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reseller extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'link',
        'link_type_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function link_type()
    {
        return $this->belongsTo(Reseller::class, 'link_type_id');
    }
}

app/Http/Controllers/Admin/ResellerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Coin;
use App\Models\Reseller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ResellerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resellers = Reseller::with('user')->get();

        return view('resellers.index', compact('resellers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('resellers.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            "name" => "required",
            "email" => "required|unique:users,email",
            "username" => "required|unique:users,username",
            "birthdate" => "required",
            "phone_number" => "required|unique:users,phone_number",
            "password" => "required",
            "shopee_link" => "sometimes",
            "tokped_link" => "sometimes",
            "bukalapak_link" => "sometimes"
        ]);

        $user = User::create(array_merge($request->all(), ["password" => Hash::make($request->password)]));
        $reseller = Reseller::create(array_merge($request->only(["shopee_link", "tokped_link", "bukalapak_link"]), ["user_id" => $user->id]));
        $coin = Coin::create(["user_id" => $user->id, "value" => 0]);

        return redirect(route('reseller.index'))->with('status', 'item stored successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Reseller $reseller
     * @return \Illuminate\Http\Response
     */
    public function show(Reseller $reseller)
    {
        return view('resellers.show', compact('reseller'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Reseller $reseller
     * @return \Illuminate\Http\Response
     */
    public function edit(Reseller $reseller)
    {
        return view('resellers.create-edit', compact('reseller'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Reseller $reseller
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Reseller $reseller)
    {
        $validated = $this->validate($request, [
            "name" => "required",
            "email" => "required|unique:users,email",
            "username" => "required|string|unique:users,username",
            "birthdate" => "required",
            "phone_number" => "required|unique:users,phone_number",
            "shopee_link" => "sometimes",
            "tokped_link" => "sometimes",
            "bukalapak_link" => "sometimes",
            "coins_value" => "sometimes|integer"
        ]);

        $reseller->user->first()->update(array_merge($request->all(),
            ['password' => $request->password ? Hash::make($request->password) : $reseller->user->first()->password]));
        $reseller->update($request->all());
        $reseller->coin->first()->update(['value' => $request->coins_value ?? $reseller->coin->value]);

        return redirect(route('reseller.index'))->with('success', 'item updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reseller $reseller
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reseller $reseller)
    {
        $reseller->delete();

        return redirect(route('reseller.index'))->with('success', 'item deleted successfully');
    }
}

resources/views/resellers/create-edit.blade.php
@extends('layout.page')

@section('title', 'Reseller')

@section('header-content')

@endsection

@section('page-content')
<x-card.layout>
    <x-slot name="header">
        {{ request()->routeIs('reseller.create') ? 'Create Reseller' : 'Update Reseller' }}
    </x-slot>
    <x-slot name="body">
        <form id="form"
            action="{{ request()->routeIs('reseller.create') ? route('reseller.store'): route('reseller.update', @$reseller->id) }}"
            class="theme-form mega-form" method="post" enctype="multipart/form-data">
            @csrf
            <x-forms.put-method />
            <input type="hidden" name="roles_id" value="reseller">
            <x-forms.input required="" label="Nama Lengkap" name="name" :value="@$reseller->user->name" />
            <x-forms.input required="" label="Email" name="email" :value="@$reseller->user->email" />
            <x-forms.input required="" label="Username" name="username" :value="@$reseller->user->username" />
            <x-forms.date label="Tanggal Lahir" name="birthdate" :value="@$reseller->user->birthdate" />
            <x-forms.input required="" label="Phone Number" type="number" name="phone_number" :value="@$reseller->user->phone_number" />
            <x-forms.text password="1" label="Password" name="password" :value="@$reseller->user->passwords" />

        </form>
        <button form="form" class="btn btn-primary btn-pill">Submit</button>
        <x-action.cancel />
    </x-slot>
</x-card.layout>
@endsection

@section('footer-content')

@endsection

resources/views/resellers/index.blade.php
@extends('layout.page')

@section('title', 'Reseller')

@section('header-content')

@endsection

@section('page-content')
<x-card.layout >
    <x-slot name="header">
        <x-card.h-buat url="{{route('reseller.create')}}" title="Reseller"/>
    </x-slot>

    <x-slot name="body">
        <table class="table table-striped">
            <thead>
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Action</th>
            </thead>
            <tbody>
                @foreach ($resellers as $each)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$each->user->name}}</td>
                        <td>{{$each->user->email}}</td>
                        <td>{{$each->user->phone_number}}</td>
                        <td class="text-center">
                            <div class="d-flex">
                                <x-action.edit action="{{route('reseller.edit', $each->id)}}" />
                                <x-action.delete :ident="$each->id" action="{{route('reseller.destroy', $each->id)}}" />
                            </div>
                            <a href="{{route('coin.edit', $each->user->coin->id)}}" class="btn btn-sm mx-1 my-1 btn-primary">Update Coin</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </x-slot>
</x-card.layout>
@endsection

@section('footer-content')

@endsection

resources/views/resellers/show.blade.php
@extends('layout.page')

@section('title', 'Reseller')

@section('header-content')

@endsection

@section('page-content')
<div class="mt-4">
    <div class="col-12 col-xl-10 order-1 order-xl-0">
        <div class="card shadow-none border border-300 my-4" data-component-card>
            <div class="card-header p-4 border-bottom border-300 bg-soft">
              <div class="row g-3 justify-content-between align-items-center">
                <div class="col-12 col-md">
                  <h3 class="text-900 mb-0" data-anchor> Title </h3>
                </div>
              </div>
            </div>
            <div class="card-body">

            </div>
          </div>
    </div>
</div>
@endsection

@section('footer-content')

@endsection