routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AddressController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CoinController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FavoriteController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentMethodController;
use App\Http\Controllers\Admin\ProductCategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductImageController;
use App\Http\Controllers\Admin\ProductPriceController;
use App\Http\Controllers\Admin\ProductSubcategoryController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\ResellerController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\Admin\SliderPromoController;
use App\Http\Controllers\Admin\VoucherController;
use App\Http\Controllers\AdminLoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AdminLoginController::class, 'index'])->name('admin.login.index');
Route::post('/post', [AdminLoginController::class, 'login'])->name('admin.login');
Route::get('/logout', [AdminLoginController::class, 'logout'])->name('admin.logout');

Route::get('/', function(){
    return redirect(route('admin.login.index'));
});

Route::group(['middleware'=>'auth:admin'], function() {
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/admin', AdminController::class);
    Route::resource('/about', AboutController::class);
    Route::resource('/address', AddressController::class);
    Route::resource('/cart', CartController::class);
    Route::resource('/coin', CoinController::class);
    Route::resource('/customer', CustomerController::class);
    Route::resource('/faq', FaqController::class);
    Route::resource('/favorite', FavoriteController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/product', ProductController::class );
    Route::resource('/payment_method', PaymentMethodController::class);
    Route::resource('/product_category', ProductCategoryController::class);
    Route::resource('/product_subcategory', ProductSubcategoryController::class);
    Route::resource('/product_image', ProductImageController::class);
    Route::resource('/product_price', ProductPriceController::class);
    Route::resource('/reseller', ResellerController::class);
    Route::resource('/shipping', ShippingController::class);
    Route::resource('/slider_promo', SliderPromoController::class);
    Route::resource('/voucher', VoucherController::class);
    Route::resource('/city', CityController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/district', DistrictController::class);

    Route::delete('/product_price/wholesaler/{wholesaler}', [ProductPriceController::class, 'destroyWholesaler'])->name('wholesaler.delete');
    Route::get('/coin/{coin}/history', [CoinController::class, 'coinhistory']);
});


//Admin Home page after login

app/Models/Shipping.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shipping extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'est_deliver'
    ];

    public function order()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/Admin/ShippingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Shipping;
use Illuminate\Http\Request;

class ShippingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shippings = Shipping::all();

        return view('shippings.index', compact('shippings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shippings.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            "name" => "required",
            "est_deliver" => "required"
        ]);

        Shipping::create($request->all());

        return redirect(route('shipping.index'))->with('status', 'item stored successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Shipping $shipping
     * @return \Illuminate\Http\Response
     */
    public function show(Shipping $shipping)
    {
        return view('shippings.show', compact('shipping'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Shipping $shipping
     * @return \Illuminate\Http\Response
     */
    public function edit(Shipping $shipping)
    {
        return view('shippings.create-edit', compact('shipping'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Shipping $shipping
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Shipping $shipping)
    {
        $validated = $this->validate($request, [
            "name" => "required",
            "est_deliver" => "required"
        ]);

        $shipping->update($validated);

        return redirect(route('shipping.index'))->with('success', 'item updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Shipping $shipping
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shipping $shipping)
    {
        $shipping->delete();

        return redirect(route('shipping.index'))->with('success', 'item deleted successfully');
    }
}

resources/views/shippings/create-edit.blade.php
@extends('layout.page')

@section('title', 'Shipping')

@section('header-content')

@endsection

@section('page-content')
<div class="mt-4">
    <div class="col-12 col-xl-10 order-1 order-xl-0">
        <div class="card shadow-none border border-300 my-4" data-component-card>
            <div class="card-header p-4 border-bottom border-300 bg-soft">
              <div class="row g-3 justify-content-between align-items-center">
                <div class="col-12 col-md">
                  <h3 class="text-900 mb-0" data-anchor> Title </h3>
                </div>
              </div>
            </div>
            <div class="card-body">
                <form action="{{route()}}">

                    <button type="submit" class="btn btn-primary">Buat</button>
                  </form>
            </div>
          </div>
    </div>
</div>
@endsection

@section('footer-content')

@endsection

resources/views/shippings/edit.blade.php
@extends('layout.page')

@section('title', 'Shipping')

@section('header-content')

@endsection

@section('page-content')
<div class="mt-4">
    <div class="col-12 col-xl-10 order-1 order-xl-0">
        <div class="card shadow-none border border-300 my-4" data-component-card>
            <div class="card-header p-4 border-bottom border-300 bg-soft">
              <div class="row g-3 justify-content-between align-items-center">
                <div class="col-12 col-md">
                  <h3 class="text-900 mb-0" data-anchor> Title </h3>
                </div>
              </div>
            </div>
            <div class="card-body">

            </div>
          </div>
    </div>
</div>
@endsection

@section('footer-content')

@endsection

resources/views/shippings/index.blade.php
@extends('layout.page')

@section('title', 'Shipping')

@section('header-content')

@endsection

@section('page-content')
<x-card.layout >
    <x-slot name="header">
        <x-card.h-buat url="{{route('shipping.create')}}" title="Shipping"/>
    </x-slot>

    <x-slot name="body">
        <table class="table table-striped">
            <thead>

            </thead>
            <tbody>

            </tbody>
        </table>
    </x-slot>
</x-card.layout>
@endsection

@section('footer-content')

@endsection

resources/views/shippings/show.blade.php
@extends('layout.page')

@section('title', 'Shipping')

@section('header-content')

@endsection

@section('page-content')
<div class="mt-4">
    <div class="col-12 col-xl-10 order-1 order-xl-0">
        <div class="card shadow-none border border-300 my-4" data-component-card>
            <div class="card-header p-4 border-bottom border-300 bg-soft">
              <div class="row g-3 justify-content-between align-items-center">
                <div class="col-12 col-md">
                  <h3 class="text-900 mb-0" data-anchor> Title </h3>
                </div>
              </div>
            </div>
            <div class="card-body">

            </div>
          </div>
    </div>
</div>
@endsection

@section('footer-content')

@endsection